---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu1704
    image: ubuntu:17.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: no_passphrase
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../conftest.py
  lint:
    name: flake8
