---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu1404
    image: ubuntu:14.04
  - name: ubuntu1604
    image: ubuntu:16.04
  - name: ubuntu1704
    image: ubuntu:17.04
  - name: debian8
    image: debian:8
  - name: debian9
    image: debian:9
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: options
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../conftest.py
  lint:
    name: flake8
