---
- name: Converge
  hosts: all
  tasks:
    - name: Include wpa_supplicant role
      include_role:
        name: ansible-wpa_supplicant-role
      vars:
        wpa_ap_scan: 1
        wpa_cli_reconfigure: yes
        wpa_country: GB
        wpa_ctrl_interface: madeup
        wpa_passphrase: yes
        wpa_update_config: 0
        wpa_networks:
          - ssid: test
            psk: testtest
            priority: 1
            id_str: testOne
          - ssid: test2
            psk: testtest2
            priority: 2
            id_str: testTwo
          - ssid: testing
            key_mgmt: NONE
          - ssid: yourHiddenSSID
            scan_ssid: 1
            psk: Your_wifi_password
          - ssid: 1x-test
            scan_ssid: 1
            key_mgmt: IEEE8021X
            eap: TLS
            identity: user@example.com
            ca_cert: /etc/cert/ca.pem
            client_cert: /etc/cert/user.pem
            private_key: /etc/cert/user.prv
            private_key_passwd: password
            eapol_flags: 3
